name: Fabric CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runTests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: "Add Java 17"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: "Run Fabric Tests"
        uses: Geometrically/fabric-test-runner@v1
        with:
          minecraftVersion: 1.20.4
          runBuildTest: false

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: Builds
          path: build/libs
